var config = {
	'vendor-css-config' : [	'bower_components/bootstrap/dist/css/bootstrap.css',
	                        'bower_components/flexslider/flexslider.css',
	                        'bower_components/datatables/media/css/jquery.dataTables.css',
	                        'bower_components/blueimp-file-upload/css/jquery.fileupload.css',
	                        'bower_components/blueimp-file-upload/css/jquery.fileupload-ui.css',
	                        'bower_components/blueimp-file-upload/css/jquery.fileupload-noscript.css',
	                        'bower_components/blueimp-file-upload/css/jquery.fileupload-ui-noscript.css',
	                        'bower_components/angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.css',
	                        'bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css',
	                        'bower_components/jquery-ui/themes/smoothness/jquery-ui.css'],

    'base-js-config'    : ['development-env/css/application.css'],

    'application-js-config' : ['development-env/scripts/baseApp/app.js',
			                   'development-env/scripts/baseApp/factory/HttpInterceptor.js',
			                   'development-env/scripts/baseApp/providers/routes.js',                         
			                   'development-env/scripts/baseApp/controllers/NavigationController.js',
			                   'development-env/scripts/commonApp/app.js',
			                   'development-env/scripts/commonApp/controllers/CommonWorkflowController.js',
			                   'development-env/scripts/commonApp/controllers/PrototypeController.js',
			                   'development-env/scripts/commonApp/controllers/ModuleController.js'],
    'vendor-js-config'  : ["bower_components/jquery/dist/jquery.js",
                              "bower_components/es5-shim/es5-shim.js",
                              "bower_components/angular/angular.js",
                              "bower_components/jquery-ui/jquery-ui.js",
                              "bower_components/bootstrap/dist/js/bootstrap.js",
                              "bower_components/checklist-model/checklist-model.js",
                              "bower_components/angular-route/angular-route.js",
                              "bower_components/angular-ui-slider/src/slider.js",
                              "bower_components/angular-bootstrap/ui-bootstrap-tpls.js",
                              "bower_components/jquery.customSelect/jquery.customSelect.js",
                              "bower_components/flexslider/jquery.flexslider.js",
                              "bower_components/jquery-mousewheel/jquery.mousewheel.js",
                              "bower_components/datatables/media/js/jquery.dataTables.js",
                              "bower_components/datatable-fixedColumns/js/dataTables.fixedColumns.js",
                              "bower_components/angular-ui-scroll/dist/ui-scroll.js",
                              "bower_components/angular-ui-scrollpoint/dist/scrollpoint.js",
                              "bower_components/angular-ui-event/dist/event.js",
                              "bower_components/angular-ui-mask/dist/mask.js",
                              "bower_components/angular-ui-validate/dist/validate.js",
                              "bower_components/angular-ui-indeterminate/dist/indeterminate.js",
                              "bower_components/angular-ui-uploader/dist/uploader.js",
                              "bower_components/angular-ui-utils/index.js",
                              "bower_components/angular-ui-utils-jq/jq.js",
                              "bower_components/angular-animate/angular-animate.js",
                              "bower_components/blueimp-file-upload/js/jquery.fileupload.js",
                              "bower_components/blueimp-file-upload/js/jquery.fileupload-process.js",
                              "bower_components/blueimp-file-upload/js/jquery.fileupload-validate.js",
                              "bower_components/blueimp-file-upload/js/jquery.fileupload-angular.js",
                              "bower_components/blueimp-file-upload/js/jquery.iframe-transport.js",
                              "bower_components/awsaccordion/jquery.accordion.js",
                              "bower_components/jquery.numeric/index.js",
                              "bower_components/jquery.rotaterator/index.js",
                              "bower_components/moment/moment.js",
                              "bower_components/underscore/underscore.js",
                              "bower_components/hc-utils/hc-utils.js",
                              "bower_components/jquery.maskedinput/dist/jquery.maskedinput.js",
                              "bower_components/angular-datatables/dist/angular-datatables.js",
                              "bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.js",
                              "bower_components/angular-datatables/dist/plugins/colreorder/angular-datatables.colreorder.js",
                              "bower_components/angular-datatables/dist/plugins/columnfilter/angular-datatables.columnfilter.js",
                              "bower_components/angular-datatables/dist/plugins/light-columnfilter/angular-datatables.light-columnfilter.js",
                              "bower_components/angular-datatables/dist/plugins/colvis/angular-datatables.colvis.js",
                              "bower_components/angular-datatables/dist/plugins/fixedcolumns/angular-datatables.fixedcolumns.js",
                              "bower_components/angular-datatables/dist/plugins/fixedheader/angular-datatables.fixedheader.js",
                              "bower_components/angular-datatables/dist/plugins/scroller/angular-datatables.scroller.js",
                              "bower_components/angular-datatables/dist/plugins/tabletools/angular-datatables.tabletools.js",
                              "bower_components/angular-ui-router/release/angular-ui-router.js",
                              "bower_components/angular-sanitize/angular-sanitize.js",
                              "bower_components/angular-input-modified/src/angular-input-modified.js",
                              "bower_components/ui-router-extras/release/ct-ui-router-extras.js",
                              "bower_components/angular-messages/angular-messages.js",
                              "bower_components/angular-translate/angular-translate.js",
                              "bower_components/ng-idle/angular-idle.js",
                              "bower_components/angular-promise-tracker/promise-tracker.js",
                              "bower_components/angular-unsavedChanges/dist/unsavedChanges.js",
                              "bower_components/jquery-placeholder/jquery.placeholder.js",
                              "bower_components/bootstrap-switch/dist/js/bootstrap-switch.js",
                              "bower_components/jquery.nicescroll/jquery.nicescroll.js",
                              "bower_components/angular-scroll/angular-scroll.js",
                              "bower_components/autoNumeric/autoNumeric.js",
                              "bower_components/highcharts-release/highcharts.js",
                              "bower_components/highcharts-release/highcharts-more.js",
                              "bower_components/highcharts-release/modules/exporting.js",
                              "bower_components/lodash/lodash.js",
                              "bower_components/Read-More-Directive/js/directives/readmore.js",
                              "bower_components/ng-tags-input/ng-tags-input.min.js",
                              "bower_components/angular-utf8-base64/angular-utf8-base64.js",
                              "bower_components/multiple-select/jquery.multiple.select.js",
                              "bower_components/flexslider/jquery.flexslider-min.js",
                              "bower_components/angular-promise-tracker/promise-tracker-http-interceptor.js"
                    ],
      'properties-js-config'  : ['development-env/properties/messages.js']          
}
module.exports = config;



